# -*- coding: utf-8 -*-
"""demo1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1WFV0NoLpUmAMRy432VTrpneumrJaY1U6
"""

print("Hello World!")

a = 10
b = 5
sum = a + b
sum

