# -*- coding: utf-8 -*-
"""Exp1_25UAM134.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1IIRSKyU5_L7Bv0Ak-lRu2yiX5zh0hGj9
"""

#----------------------Exp 01-------------------------------------------
print("Hello , World!")

if 5 > 2:
  print("Five is greater than two!")

myvar = "John"
my_var = "John"
_my_var = "John"
myVar = "John"
MYVAR = "John"
myvar2 = "John"

print(myvar)
print(my_var)
print(_my_var)
print(myVar)
print(MYVAR)
print(myvar2)

2myvar = "John"
my-var = "John"
my var = "John"

x = 5
print(type(x))

x = 1 # int
y = 2.8 # float
z = 1j # complex


print(type(x))
print(type(y))
print(type(z))

x = 1
y = 35656222554887711
z = -3255522

print(type(x))
print(type(y))
print(type(z))

x = 1.10
y = 1.0
z = -35.59
print(type(x))
print(type(y))
print(type(z))

x = 3+5j
y = 5j
z = -5j
print(type(x))
print(type(y))
print(type(z))

print("Hello")
print('Hello')

a = "Hello"
print(a)

print(10 > 9)
print(10 == 9)
print(10 < 9)

a = 200
b = 33

if b > a:
  print("b is greater than a")
else:
  print("b is not greater than a")