# -*- coding: utf-8 -*-
"""EXP2_25UAM134.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1U8HVx-FH6lnnyNIuGGoWVN33MhbNzoYg
"""

# Define a sample messy string
phrase = " Learning Python is fun! "

print("Original Phrase:", repr(phrase))
print()

# 1. upper() & lower() - Case conversion
print("1. Upper Case:", phrase.upper())
print(" Lower Case:", phrase.lower())


# 2. strip() - Removes leading and trailing whitespaces
cleaned_phrase = phrase.strip()
print("2. Cleaned (strip):", repr(cleaned_phrase))


# 3. replace() - Replaces a substring with another
replaced_text = cleaned_phrase.replace("fun", "awesome")
print("3. Replaced Text:", replaced_text)


# 4. split() - Splits a string into a list based on a delimiter
word_list = cleaned_phrase.split(" ")
print("4.split into List:", word_list)


#5.join()-Merges a list of strings into one string
joined_text= "_".join(word_list)
print("%.Joined with Hyphen:", joined_text)


# 6. find() & index() - Searches for a substring and returns its index
print("6. Index of 'Python' (find):", cleaned_phrase.find("Python"))


# 7. count() - Counts occurrences of a substring
print("7. Count of letter 'n':", cleaned_phrase.count("n"))


# 8. startswith() & endswith() - Boolean validation checks
print("8. Starts with 'Learning'?:", cleaned_phrase.startswith("Learning"))
print(" Ends with '!'?:", cleaned_phrase.endswith("!"))


# 9. isalpha() & isdigit() - Character type checks
print("9. Is '12345' numeric?:", "12345".isdigit())
print(" Is 'Python' purely alphabetic?:", "Python".isalpha())

#-------------------Exp 02------------------

#define sample string
text = "PythonProg"

#-----------------------------
#i. Accessing charraster by indexing
#-----------------------------

print("---1)String indexing---")

#positive indexing : starts from 0(Left to Right)
print("First character(Positive index 0):",text[0])
print("Sixth character(Positive index 5):",text[5])

#negative Indexing:Starts from -1(Right to Left)
print("Last character(Negative index -1):",text[-1])
print("Second to last character(Negative index -2):",text[-2])
print()



#-----------------------------------------
#ii. Accessing substring by slice operator
#syntax : string[start : stop : step]
#-----------------------------------------

print("---2)String slicing---")

#Basic slice(Extracts from index 0 up to 6, exclusive)
print("Slice[0:6]:", text[0:6])

#slicing with default start index (Omitting start default to 0)
print("Slice[:6]:", text[:6])

#slicing with default stop index (Omitting stop goes to end)
print("Slice[6:]:", text[6:])

# Slicing with negative indices
print("Slice [-4:-1]:", text[-4:-1])

# Slicing with a stride/step (Extracts every second character)
print("Slice [::2]:", text[::2])

# Reversing a string using a negative step
print("Reversed string [::-1]:", text[::-1])

