# -*- coding: utf-8 -*-
"""EXP3_25UAM134.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/16Js2sCiKvftpV0t_FyflXHx7OC-oxIvI
"""

#------- Experiment 3 -------
#Demonstrate use of conditional statement : a)"if" b)"if...else" c) nested "if" using python

# 1.
i = 10
if i > 15:
  print("10 is less than 15")
print("I am Not in if")

#2.
i = 20
if i > 0:
  print("i is positive")

else:
  print("i is ) or negative")

#3.
a = -2
res = "Positive" if a >= 0 else "Negative"
print(res)

#4.
i=10
if i==10:

  if i<15:
    print("i is smaller than 15")

  if i<12:
    print("i is smaller than 12 too")

  else:
    print("i is greater than 15")

else:
  print("i is not equal to 10")

#Determine whether the number is even or odd

a = 10
b = 3

if a % 2 == 0:
  print("even")
else:
  print("odd")


#Determine whether person is eligible or not to vote

a = 20

if a==18:
  print("Person is eligible for vote")

if a>18:
  print("Person is eligible for vote")

else:
  print("Not eligible to vote")


#Pass or Fail

a = 65

if a>=50:
  print("Pass")

else:
  print("Fail")


#Check wheether number is positive, negative or zero

a = 12

if a>0:
  print("Postive")

  if a<0:
   print("Negative")

   if a==0:
    print("zero")

#Calculate electricity bills
units=int(input("Enter the units:"))
if units<=100:
  bill=0

elif units<=200:
  bill=(units-100)*5

else:
  bill=(100*5) + (units-200)*10

print("electricity bill = ",bill)


#Display the last digit of number
num=int(input('Enter the number:'))

lastdigit =num%10
print("Last digit is:",lastdigit)


#Last digit is divisible by 3 or not
num=int(input('Enter the number:'))

lastdigit =num%10

if lastdigit%3==0:
  print("Last digit is divisible by 3")

else:
  print("Last digit is not divisible by 3")