# -*- coding: utf-8 -*-
"""EXP4_25UAM134.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1jNBxEZkdc8F744Jn5u5SUR5lBrqDB9CO
"""

#---EXPERIMENT 4---
#Demonstrate use of looping statements: a) ‘while’ loop b) ‘for’ loop c) Nested loops.

#For
L1=['A','B', 'C', 'D', 'E']

for L1 in L1:
  print(L1)

#-----
fruits=["apple", "banana", "mango"]

for x in fruits:
  print(x)


#-----
fruits=["apple", "banana", "mango"]

for x in fruits:
  print(x)

  if x=="banana":
    break
    print(x)


  #----
  fruits = ["apple", "banana", "mango"]
for x in fruits:
  if x == "banana":
    continue
  print(x)

#Range
for x in range(6):
  print(x)

#---
for x in range(2,6):
  print(x)

#---
for x in range(2, 30, 3):
  print(x)

#----
for x in range(6):
  if x==3 : break
  print(x)
else:
  print("Finally finished!")

#Nested Loops
adj = ["red", "big", "tasty"]
fruits = ["apple", "banana", "cherry"]

for x in adj:
  for y in fruits:
    print(x, y)

# The Pass Statement
for x in [0, 1, 2]:
  pass
  print(x)

#While
i = 1
while i < 6:
  print(i)
  i += 1

#----
i = 1
while i < 6:
  print(i)
  if i == 3:
    break
  i += 1

#----
i = 0
while i < 6:
  i += 1
  if i == 3:
    continue
  print(i)

#reverse the string using for loop
#----
s = "W#SCHOOL"

for s in range():
  print(s)