# -*- coding: utf-8 -*-
"""EXP5_25UAM134.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1e-4DOjxR0N-zWMIO5SQYAW6E8-ZkOzO5
"""

#Demonstrate the functions/methods which on the list in python with suitable example
F1_list=['abcd', 147, 2.43, 'Tom', 74.9]
small_list=[111, 'Tom']
print(F1_list)
print(F1_list[0])
print(F1_list[1:3])
print(small_list*2)
print(F1_list+small_list)
del F1_list[2]
print(F1_list)
F1_list.append('Jerry')
print(F1_list)
F1_list.count('Tom')
print(F1_list)
F1_list.extend(small_list)
print(F1_list)
F1_list.index('Tom')
print(F1_list)
F1_list.insert(1, 'Tom')
print(F1_list)
F1_list.pop(1)
print(F1_list)
F1_list.remove('Tom')
print(F1_list)
F1_list.reverse()
print(F1_list)
print(len(F1_list))
print(type(F1_list))
F1_list.insert(1, "Spike")
print(F1_list)