# -*- coding: utf-8 -*-
"""Workshop1aug.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1o7kEw01w1broy8-98a9QsQlQaR-NCSHy
"""

#cell

#indentifier
#100 is object

a = 100
a


b = 'Amit'
b

id(a)

c = []
type(c)

d = ()
type(d)

type(a)

# rules
# PEPB style guide
# a-z, A-Z are allow

bank_tfsc='8763254'

1num=100

import keyword
print(keyword.kwlist)

len(keyword.kwlist)

as = 'Puja'
#we do not use reserved keywords as a lables



"""#Operators in Python

"""

#Arithmatic operators

#1.//float division operator

10/4

10//4

8/3

8//3

3/2

3//2

#2.** power of operator or exponential operator

3**3

# Assignment operator
num = 10

num + 50

num

num += 50 #num = num + 50

num

num -= 50

num

# Logical operator
name = 'raj'
age = 20
# and
(name == 'raj')and(age == 20)

(name == 'shreya')or(age == 20)

# python is case sensitive

(name == 'shreya')or(age == 21)

(name == 'raj')and(age == 20)

(name == 'shreya')and(age == 21)

#not - negation
not name == 'shreya'

#Membership operator important for searching operation
'Sachin' in 'Sachin Tendulakar'

'10' not in 'Sachin Tendulakar'

'10' in 'Sachin Tendulakar'

100 in [11, 100, 20, 300]

'raj' in [11, 100, 20, 300]

"""#Data Types"""

# numeric - int, float, complex
#string
x = 'python'
type(x)

y = "c++"
type(y)

#feature of string
#Background data structure of a str is an Array
#    -6      -2 -1
#s = 'P|Y|T|H|O|N|
#     0 1 2 3 4 5
# Index : number assigned to each block

t = 'PYTHON'
t[0]

t[-2]

"\u0909" #unicourse

'\u0950'

#slicing
s = 'python is simple and easy'
#s[start_index:stop_index]
s[0:6]

s[1:4]

s[0:]

s[:]

s[0:16]

#s[start_index:stop_index:step]
# reverse the string
s[::-1]

"""#Methods of String"""

s.upper() #temp

s.title()

s.capitalize()

s.endswith

s.swapcase

help(str.upper)

help(str.title)

# List
#[]
e = [] # empty list
e

e.append('shreya')

e

e.append(200)
e

e.remove('raj')

e.remove(200)

e

e.remove(200)
e.remove(200)
e.remove(200)

e

r = [8, 999, 2, 0]
r

r.reverse()

r

r.sort()

r

r.sort(reverse=True)

r

#remove all elements from list
r.clear()
r

"""#Tuple"""

t = ()
t
type(t)

t.append(40)

t1 = [10, 20, 30]
t2 = (10, 20, 30)

t1

t2

t1[-1] = 'Shreya'

t1

t2[-1] = 'Shreya'

"""#Set"""

s = {10, 20, 30, 40}
s

type(s)

#duplicates values are not allowed
{10, 20, 10, 10, 20, 10, 20, 20, 10}

# doesnt preserves the sequence order
{999, 'A', 11, 0, 'k', 2, '8'}

s

s[0] #indexing is not allowed

s[:-1]

s[::-1] # slicing not allowed

s

s.add(50)

s

# set is mutable in nature
s.update({'A', 'B', 'C'})

s

s.pop()  # remove random element

s.pop()

s

s.remove(50)  # remove perticular element

s

s.add(40)

s

s.add(10)

s

"""#**Dictionary**"""

#{key:value/s}
# key is case sensitive
d = {'name':'Ram','place':'Pune','pincode':411012}
d

d['name']

d['place']

d['pincode'] = 411091

d

d.keys()  # if we want to access keys only

d.values() # if we want to access values only

d.items()  # if we want both keys and values

"""#**Flow Control Blocks**"""

# selective or conditional statement
num = int(input('Enter a number: '))

if num<0:
  print(num,"num is negative")

else:
  print(num,"num is positive")

num = int(input('Enter a number: '))

if num%2==0:
  print(num,"num is even")

else:
  print(num,"num is odd")

signal= input('Enter the signal:')
signal=signal.lower()
if signal=='orange':
  print("wait")

elif signal=='red':
  print("Stop")

else:
  print("go")

#iterative statements
#for loop-> it used to iterate over the sequence
# means it loads one element at a time to form the collection

f = [20, 1, 40, 55]
for num in f:
  if num%2==0:
    print(num+100)

#Ps: create 2 seperate list 1 for even and 1 for odd
even =[]
odd =[]
for num in f:
  if num%2==0:
    even.append(num)

  else:
    odd.append(num)

print('odd number:',odd)
print('Even number:',even)

# while loop
num = 1
while num<5:
  print(num)

num = 1
while num<5:
  print(num)
  num+=1

#print 1 to 5
for i in range(1,6):
  print(i)

"""#**Module**"""

# a python file is called module  .py
# Python does support modular programming
import math

math.pi

math.e

math.factorial(6),math.sqrt(625)

!pip install "qrcode[pil]"

import qrcode
# simple qrcode
url=input('Enter URL:')
img = qrcode.make(url)
img.save("basic_qr.png")

"""#**List Comprehension**"""

#create a list of 1 to 10 aquare of nubmber
{num**2 for num in range(1, 11)}

{num**2 for num in range(1,11)}

nms=['shneha', 'amit', 'puja', 'ankit']
[nm.upper() for nm in nms if nm.endswith('a')]

"""#**Function**"""

def info(name,place,age):  #function declaration
 print("Your name is :",name)
 print("Your place is :",place)
 print("Your age is :",age)

name=input('Enter name:')
place=input('Enter place:')
age=int(input('Enter age:'))
info(name,place,age)  #function calling

"""#**Lambda function**"""

convert = lambda nm:nm.upper()
convert(input('Enter info:'))

#lambda parameter's:expression

!pip install -U google-genai

from google import genai
key= "AQ.Ab8RN6LZiBxEwT9oXJZlcgPY7FzConGHRWa0rKEjPjgrMUNybw"
client = genai.Client[api_key=key]

interaction = client.interactions.create(
    model="gemini-3.6-flash",
    input="Explain how AI works in a few words"
)
print(interaction.output_text)

